
package View;

import ConexionSQL.PacientesBD;
import Model.Pacientes;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexis
 */
public class ClinicaSalubridad extends javax.swing.JFrame {
    ArrayList<Pacientes> pacientes;
    PacientesBD db = new PacientesBD();
    Pacientes paciente = new Pacientes();

    /** Creates new form ClinicaSalubridad */
    public ClinicaSalubridad() {
        initComponents();
        this.setTitle("Clinica de Salubridad UAM-Cuajimalpa"); // Titulo de ventana
        this.setLocationRelativeTo(null);   // Para que la ventana aparezca centrada en la pantalla
    }
    
    public void listar20kDatos() { // Con esta función se muestra la tabla
        pacientes = db.ListPacientes20k();
        DefaultTableModel tb = (DefaultTableModel)jTable1.getModel();
        for(Pacientes p: pacientes) {
            tb.addRow(new Object[]{p.getID_REGISTRO(), p.getSEXO(), p.getENTIDAD_RES(), 
            p.getTIPO_PACIENTE(), p.getFECHA_INGRESO(), p.getFECHA_SINTOMAS(), p.getEDAD(), 
            p.getRESULTADO_LAB(), p.getRESULTADO_ANTIGENO(), p.getCLASIFICACION_FINAL()});
        }
    }
    
    public void listar50kDatos() { // Con esta función se muestra la tabla
        pacientes = db.ListPacientes50k();
        DefaultTableModel tb = (DefaultTableModel)jTable1.getModel();
        for(Pacientes p: pacientes) {
            tb.addRow(new Object[]{p.getID_REGISTRO(), p.getSEXO(), p.getENTIDAD_RES(), 
            p.getTIPO_PACIENTE(), p.getFECHA_INGRESO(), p.getFECHA_SINTOMAS(), p.getEDAD(), 
            p.getRESULTADO_LAB(), p.getRESULTADO_ANTIGENO(), p.getCLASIFICACION_FINAL()});
        }
    }
    
    public void listar100kDatos() { // Con esta función se muestra la tabla
        pacientes = db.ListPacientes100k();
        DefaultTableModel tb = (DefaultTableModel)jTable1.getModel();
        for(Pacientes p: pacientes) {
            tb.addRow(new Object[]{p.getID_REGISTRO(), p.getSEXO(), p.getENTIDAD_RES(), 
            p.getTIPO_PACIENTE(), p.getFECHA_INGRESO(), p.getFECHA_SINTOMAS(), p.getEDAD(), 
            p.getRESULTADO_LAB(), p.getRESULTADO_ANTIGENO(), p.getCLASIFICACION_FINAL()});
        }
    }
    
    public void listar250kDatos() { // Con esta función se muestra la tabla
        pacientes = db.ListPacientes250k();
        DefaultTableModel tb = (DefaultTableModel)jTable1.getModel();
        for(Pacientes p: pacientes) {
            tb.addRow(new Object[]{p.getID_REGISTRO(), p.getSEXO(), p.getENTIDAD_RES(), 
            p.getTIPO_PACIENTE(), p.getFECHA_INGRESO(), p.getFECHA_SINTOMAS(), p.getEDAD(), 
            p.getRESULTADO_LAB(), p.getRESULTADO_ANTIGENO(), p.getCLASIFICACION_FINAL()});
        }
    }
    
    public void limpiarFormulario() {   // Con esta función se limpia la tabla
        DefaultTableModel tb = (DefaultTableModel)jTable1.getModel();
        for (int i=tb.getRowCount()-1; i>=0; i--)
            tb.removeRow(i);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        BotonLimpiar = new javax.swing.JButton();
        BotonBuscar20k = new javax.swing.JButton();
        BotonBuscar50k = new javax.swing.JButton();
        BotonBuscar100k = new javax.swing.JButton();
        BotonBuscar250k = new javax.swing.JButton();
        BotonVer20k = new javax.swing.JButton();
        BotonVer50k = new javax.swing.JButton();
        BotonVer100k = new javax.swing.JButton();
        BotonVer250k = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_REGISTRO", "SEXO", "ENTIDAD_RES", "TIPO_PACIENTE", "FECHA_INGRESO", "FECHA_SINTOMAS", "EDAD", "RESULTADO_LAB", "RESULTADO_ANTIGENO", "CLASIFICACION_FINAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Buscar Paciente en 20k");

        jLabel2.setText("Buscar Paciente en 50k");

        jLabel3.setText("Buscar Paciente en 100k");

        jLabel4.setText("Buscar Paciente en 250k");

        BotonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Limpiar.png"))); // NOI18N
        BotonLimpiar.setText("LImpiar Tabla");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });

        BotonBuscar20k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buscar.png"))); // NOI18N
        BotonBuscar20k.setText("Buscar en 20k");
        BotonBuscar20k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscar20kActionPerformed(evt);
            }
        });

        BotonBuscar50k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buscar.png"))); // NOI18N
        BotonBuscar50k.setText("Buscar en 50k");
        BotonBuscar50k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscar50kActionPerformed(evt);
            }
        });

        BotonBuscar100k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buscar.png"))); // NOI18N
        BotonBuscar100k.setText("Buscar en 100k");
        BotonBuscar100k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscar100kActionPerformed(evt);
            }
        });

        BotonBuscar250k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buscar.png"))); // NOI18N
        BotonBuscar250k.setText("Buscar en 250k");
        BotonBuscar250k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscar250kActionPerformed(evt);
            }
        });

        BotonVer20k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ver.png"))); // NOI18N
        BotonVer20k.setText("Ver los 20k Registros");
        BotonVer20k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVer20kActionPerformed(evt);
            }
        });

        BotonVer50k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ver.png"))); // NOI18N
        BotonVer50k.setText("Ver los 50k Registros");
        BotonVer50k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVer50kActionPerformed(evt);
            }
        });

        BotonVer100k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ver.png"))); // NOI18N
        BotonVer100k.setText("Ver los 100k Registros");
        BotonVer100k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVer100kActionPerformed(evt);
            }
        });

        BotonVer250k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ver.png"))); // NOI18N
        BotonVer250k.setText("Ver los 250k Registros");
        BotonVer250k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVer250kActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonBuscar20k)
                    .addComponent(BotonBuscar50k)
                    .addComponent(BotonBuscar100k)
                    .addComponent(BotonBuscar250k))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonVer100k)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BotonVer50k)
                        .addComponent(BotonVer20k))
                    .addComponent(BotonVer250k))
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonLimpiar)
                .addGap(392, 392, 392))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscar20k)
                    .addComponent(BotonVer20k))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscar50k)
                    .addComponent(BotonVer50k))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscar100k)
                    .addComponent(BotonVer100k))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscar250k)
                    .addComponent(BotonVer250k))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BotonLimpiar)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void BotonVer50kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVer50kActionPerformed
        limpiarFormulario();
        listar50kDatos();
        JOptionPane.showMessageDialog(null, "Datos cargados","",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BotonVer50kActionPerformed

    private void BotonVer20kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVer20kActionPerformed
        limpiarFormulario();
        listar20kDatos();
        JOptionPane.showMessageDialog(null, "Datos cargados","",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BotonVer20kActionPerformed

    private void BotonVer100kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVer100kActionPerformed
        limpiarFormulario();
        listar100kDatos();
        JOptionPane.showMessageDialog(null, "Datos cargados","",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BotonVer100kActionPerformed

    private void BotonVer250kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVer250kActionPerformed
        limpiarFormulario();
        listar250kDatos();
        JOptionPane.showMessageDialog(null, "Datos cargados","",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BotonVer250kActionPerformed

    private void BotonBuscar20kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscar20kActionPerformed
        if (!"".equals(jTextField1.getText())) {
            String id_p = jTextField1.getText();
            paciente = db.buscarPaciente20k(id_p);
            if (paciente.getID_REGISTRO() != null) {
                JOptionPane.showMessageDialog(null, "Paciente Encontrado","",JOptionPane.INFORMATION_MESSAGE);
                jTextField1.setText("");
                limpiarFormulario();
                DefaultTableModel tb = (DefaultTableModel)jTable1.getModel();
                tb.addRow(new Object[]{paciente.getID_REGISTRO(), paciente.getSEXO(), paciente.getENTIDAD_RES(), 
                paciente.getTIPO_PACIENTE(), paciente.getFECHA_INGRESO(), paciente.getFECHA_SINTOMAS(), paciente.getEDAD(), 
                paciente.getRESULTADO_LAB(), paciente.getRESULTADO_ANTIGENO(), paciente.getCLASIFICACION_FINAL()});
            } else {
                JOptionPane.showMessageDialog(null, "Paciente No Encontrado","",JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Paciente No Encontrado","",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonBuscar20kActionPerformed

    private void BotonBuscar50kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscar50kActionPerformed
        if (!"".equals(jTextField2.getText())) {
            String id_p = jTextField2.getText();
            paciente = db.buscarPaciente50k(id_p);
            if (paciente.getID_REGISTRO() != null) {
                JOptionPane.showMessageDialog(null, "Paciente Encontrado","",JOptionPane.INFORMATION_MESSAGE);
                jTextField2.setText("");
                limpiarFormulario();
                DefaultTableModel tb = (DefaultTableModel)jTable1.getModel();
                tb.addRow(new Object[]{paciente.getID_REGISTRO(), paciente.getSEXO(), paciente.getENTIDAD_RES(), 
                paciente.getTIPO_PACIENTE(), paciente.getFECHA_INGRESO(), paciente.getFECHA_SINTOMAS(), paciente.getEDAD(), 
                paciente.getRESULTADO_LAB(), paciente.getRESULTADO_ANTIGENO(), paciente.getCLASIFICACION_FINAL()});
            } else {
                JOptionPane.showMessageDialog(null, "Paciente No Encontrado","",JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Paciente No Encontrado","",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonBuscar50kActionPerformed

    private void BotonBuscar100kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscar100kActionPerformed
        if (!"".equals(jTextField3.getText())) {
            String id_p = jTextField3.getText();
            paciente = db.buscarPaciente100k(id_p);
            if (paciente.getID_REGISTRO() != null) {
                JOptionPane.showMessageDialog(null, "Paciente Encontrado","",JOptionPane.INFORMATION_MESSAGE);
                jTextField3.setText("");
                limpiarFormulario();
                DefaultTableModel tb = (DefaultTableModel)jTable1.getModel();
                tb.addRow(new Object[]{paciente.getID_REGISTRO(), paciente.getSEXO(), paciente.getENTIDAD_RES(), 
                paciente.getTIPO_PACIENTE(), paciente.getFECHA_INGRESO(), paciente.getFECHA_SINTOMAS(), paciente.getEDAD(), 
                paciente.getRESULTADO_LAB(), paciente.getRESULTADO_ANTIGENO(), paciente.getCLASIFICACION_FINAL()});
            } else {
                JOptionPane.showMessageDialog(null, "Paciente No Encontrado","",JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Paciente No Encontrado","",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonBuscar100kActionPerformed

    private void BotonBuscar250kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscar250kActionPerformed
        if (!"".equals(jTextField4.getText())) {
            String id_p = jTextField4.getText();
            paciente = db.buscarPaciente250k(id_p);
            if (paciente.getID_REGISTRO() != null) {
                JOptionPane.showMessageDialog(null, "Paciente Encontrado","",JOptionPane.INFORMATION_MESSAGE);
                jTextField4.setText("");
                limpiarFormulario();
                DefaultTableModel tb = (DefaultTableModel)jTable1.getModel();
                tb.addRow(new Object[]{paciente.getID_REGISTRO(), paciente.getSEXO(), paciente.getENTIDAD_RES(), 
                paciente.getTIPO_PACIENTE(), paciente.getFECHA_INGRESO(), paciente.getFECHA_SINTOMAS(), paciente.getEDAD(), 
                paciente.getRESULTADO_LAB(), paciente.getRESULTADO_ANTIGENO(), paciente.getCLASIFICACION_FINAL()});
            } else {
                JOptionPane.showMessageDialog(null, "Paciente No Encontrado","",JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Paciente No Encontrado","",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonBuscar250kActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClinicaSalubridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClinicaSalubridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClinicaSalubridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClinicaSalubridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClinicaSalubridad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscar100k;
    private javax.swing.JButton BotonBuscar20k;
    private javax.swing.JButton BotonBuscar250k;
    private javax.swing.JButton BotonBuscar50k;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonVer100k;
    private javax.swing.JButton BotonVer20k;
    private javax.swing.JButton BotonVer250k;
    private javax.swing.JButton BotonVer50k;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
